development:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3000
      username: root
      password: nimbu

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3000
      username: root
      password: nimbu

production:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3000
      username: root
      password: nimbu
cucumber:
  <<: *test
